name: First Job
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  FirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: "Install dependencies needed for running tests"
        run: |
          pip3 install -r requirements.txt 
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Running unit test  
        run: |
          export FIREFOX_BINARY=/usr/bin/firefox
          mkdir ./test_output
          chmod 777 ./test_output
          python -m unittest discover -s ./src -p *_test.py
      - name: Archive code coverage results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: ./test_output/*    
      - run: echo "ğŸ This job's status is ${{ job.status }}."